hard_tabs = true
use_field_init_shorthand = true
use_try_shorthand = true
condense_wildcard_suffixes = true
fn_args_layout = "Compressed"
format_code_in_doc_comments = true
imports_granularity = "Crate"
normalize_comments = true
overflow_delimited_expr = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_modules = true
